linters:
  rubocop:
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"

fixer: true

# globally enable the fixers for this project        
fixers:
    enable: true

# find full documentation here: https://stickler-ci.com/docs